package com.myApp.utils;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2015-05-26T19:16:43.183+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://impl.infservice.server.webservice.sinosoft.cn", name = "EasyScanServicePortType")
public interface EasyScanServicePortType {

    @WebResult(name = "return", targetNamespace = "http://impl.infservice.server.webservice.sinosoft.cn")
    @Action(input = "urn:easyScanInterface", output = "urn:easyScanInterfaceResponse")
    @RequestWrapper(localName = "easyScanInterface", targetNamespace = "http://impl.infservice.server.webservice.sinosoft.cn", className = "cn.sinosoft.webservice.server.infservice.impl.EasyScanInterface")
    @WebMethod(action = "urn:easyScanInterface")
    @ResponseWrapper(localName = "easyScanInterfaceResponse", targetNamespace = "http://impl.infservice.server.webservice.sinosoft.cn", className = "cn.sinosoft.webservice.server.infservice.impl.EasyScanInterfaceResponse")
    public java.lang.String easyScanInterface(
        @WebParam(name = "inputXml", targetNamespace = "http://impl.infservice.server.webservice.sinosoft.cn")
        java.lang.String inputXml
    );
}
